// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZGxz7d7KeRh_4kB89syo7wnCznfO8ByQ',
    appId: '1:5064426749:android:50cf392b360f215f9fea94',
    messagingSenderId: '5064426749',
    projectId: 'firestore-bloc-7d52a',
    databaseURL: 'https://firestore-bloc-7d52a-default-rtdb.firebaseio.com',
    storageBucket: 'firestore-bloc-7d52a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDolPScByx8RMu2c_2doPpEmoNTk8ofc1w',
    appId: '1:5064426749:ios:529a8399c0258ed89fea94',
    messagingSenderId: '5064426749',
    projectId: 'firestore-bloc-7d52a',
    databaseURL: 'https://firestore-bloc-7d52a-default-rtdb.firebaseio.com',
    storageBucket: 'firestore-bloc-7d52a.appspot.com',
    iosClientId: '5064426749-ov6nd5kv69e0515jimo7ikskvc5jaqqi.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePushNotificationCli',
  );
}
